<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../Assets/Scripts/Simulation/*.cs" />
    <Compile Include="../../../Assets/Scripts/AI/Policy/*.cs" />
    <Compile Include="../../../Assets/Scripts/Training/Core/*.cs" />
    <Compile Include="../../../Assets/Scripts/Training/TrainingProgressHistory.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>
</Project>
