import { page, escape } from "../access/pages.mjs";
import { WEB_MATCH_VERSION } from "./store.mjs";

export function lobbyPage(user) {
  return page("Multiplayer", `<nav class="lobby-nav"><a href="/">Single player</a><a href="/access">Account</a></nav>
<p class="intro">Play a friend on a standard 7×7 board. Turns are saved online, so you can leave and come back whenever you like.</p>
<div class="find-row"><button id="find">Find online match</button><p>Join an open game, or create one for the next player to join.</p></div>
<p class="note identity">Playing as <strong>${escape(user.display_name)}</strong> · your Google account</p>
<p id="notice" role="status" aria-live="polite"></p><p id="error" role="alert"></p>
<div class="lobby-grid"><section aria-labelledby="matches-heading"><div class="section-head"><h2 id="matches-heading">Your matches</h2><button id="refresh" class="secondary small">Refresh</button></div><div id="matches"><p>Loading your matches…</p></div>
<h2>Match invitations</h2><div id="invitations"></div></section>
<section aria-labelledby="friends-heading"><h2 id="friends-heading">Friends</h2><div id="friends"></div><h2>Friend requests</h2><div id="requests"></div>
<h2>Find a player</h2><p class="note">Search a Google display name or enter an exact registered email address. Players need to sign in and be approved first. Invitations appear here; no email is sent.</p>
<form id="search-form"><label for="query">Name or email address</label><div class="search-row"><input id="query" name="query" minlength="3" maxlength="254" required autocomplete="off" placeholder="Name or exact email"><button class="small">Search</button></div></form><div id="results"></div></section></div>
<p class="note">The lobby refreshes every 10 seconds while this tab is visible. Waiting matches can be cancelled before someone joins.</p>
<section id="notifications"><h2>Phone notifications</h2><p>Get a reminder when it's your turn or someone sends you a request. On iPhone (iOS 16.4 or later), use Share → Add to Home Screen and open the game from its icon first. On Android, use Chrome's Install app or Add to Home screen option for easy access.</p>
<p id="push-status" role="status">Checking notification support…</p><div class="actions"><button id="enable-push" disabled>Enable notifications</button><button id="disable-push" class="secondary" hidden>Turn off notifications</button><button id="test-push" class="secondary" hidden>Send test notification</button><button id="install-app" class="secondary" hidden>Install app</button></div></section>`, {
    style: `main{width:min(calc(100% - 80px),960px);padding-top:40px}h1{margin-bottom:16px}h2{font-family:var(--serif);font-weight:500;font-size:25px;letter-spacing:-.03em;margin:28px 0 14px}.lobby-nav{display:flex;gap:24px;margin-bottom:22px}.intro{max-width:610px}.lobby-grid{display:grid;grid-template-columns:1.1fr 1fr;gap:56px}.find-row{display:flex;align-items:center;gap:24px;margin-top:28px}.find-row button{width:240px;margin:0;flex-shrink:0}.find-row p{margin:0;max-width:360px}.identity{margin-top:18px}.section-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.section-head h2{margin-top:12px}.small{width:auto;min-height:44px;margin:0;padding:10px 14px;font-size:13px}.entry{border-top:1px solid var(--line);padding:16px 0}.entry-title{font-weight:600;margin:0;color:var(--ink)}.entry p{margin:5px 0 10px;font-size:13px}.actions{display:flex;gap:8px;flex-wrap:wrap}.actions button,.actions a{margin:0;width:auto;min-height:44px;padding:10px 14px;font-size:13px}.actions .secondary{color:var(--ink)}.tag{font-size:11px;font-weight:600;display:inline-block;padding:4px 8px;background:#f2f2f2;margin-left:8px}.search-row{display:flex;gap:8px;margin:8px 0 16px}input{flex:1;width:0;min-width:0;min-height:48px;padding:10px 12px;border:1px solid #bdbdbd;border-radius:2px;font:inherit;font-size:14px}label{font-size:13px}input:focus-visible{outline:2px solid var(--ink);outline-offset:3px}#notice{color:var(--ink);font-weight:600;min-height:24px;margin-bottom:0}#error{margin:0}.empty{font-size:14px;margin:12px 0 22px}.note{margin-top:14px}@media(max-width:700px){main{width:calc(100% - 44px);padding-top:32px}.lobby-grid{grid-template-columns:1fr;gap:8px}.find-row{display:block}.find-row button{width:100%;margin-bottom:12px}.find-row p{max-width:none}.search-row .small{padding-inline:12px}}`,
    moduleScript: "/PWA.js",
    script: `const VERSION=${JSON.stringify(WEB_MATCH_VERSION)};
const $=id=>document.getElementById(id);let lobby=null,busy=false,searchPlayers=[];
const messages={APPROVED_ACCOUNT_REQUIRED:'Please sign in again with an approved Google account.',ORIGIN_REJECTED:'Please reload this page and try again.',CONFLICT:'This game changed. Refresh to see its latest state.',MATCH_ALREADY_STARTED:'Someone has joined this match. Refresh to open it.',MATCH_CANCELLED:'This waiting match was cancelled.',RATE_LIMITED:'Please wait a minute before trying again.',UPDATE_REQUIRED:'Please reload to get the current game version.',PLAYER_NOT_FOUND:'This player could not be found.',TOO_MANY_MATCHES:'You already have 20 active matches. Finish or cancel one first.',SEARCH_TOO_SHORT:'Enter at least three characters.',MULTIPLAYER_UNAVAILABLE:'Multiplayer is temporarily unavailable. Please try again shortly.'};
async function api(path,body){const response=await fetch('/api/multiplayer/'+path,{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json','X-BlockNations-Web':'1'}:{},body:body?JSON.stringify(body):undefined});let result;try{result=await response.json()}catch{throw new Error('Multiplayer is temporarily unavailable. Please try again shortly.')}if(!response.ok||!result.ok)throw new Error(messages[result.error]||'That request could not be completed. Refresh and try again.');return result}
function node(tag,text,cls){const element=document.createElement(tag);if(text!==undefined)element.textContent=text;if(cls)element.className=cls;return element}
function entry(container,title,detail){const row=node('div',undefined,'entry');row.append(node('p',title,'entry-title'));if(detail)row.append(node('p',detail));const actions=node('div',undefined,'actions');row.append(actions);container.append(row);return actions}
function empty(container,text){container.append(node('p',text,'empty'))}
function button(actions,label,action,secondary=true){const control=node('button',label,secondary?'secondary':'');control.type='button';control.disabled=busy;control.addEventListener('click',()=>run(action));actions.append(control);return control}
function play(actions,match,label='Open match'){const link=node('a',label,'button');link.href='/?match='+match.id;actions.append(link)}
function friendState(player){return lobby?.friendships.find(link=>link.player?.id===player.id)}
function socialActions(actions,player){if(!player)return;const link=friendState(player);if(link?.status==='accepted')actions.append(node('span','Friend','tag'));else if(link?.status==='pending')actions.append(node('span',link.incoming?'Friend request received':'Friend request sent','tag'));else button(actions,'Add friend',async()=>{await api('friend-request',{playerId:player.id});$('notice').textContent='Friend request sent to '+player.name+'.';await refresh()});button(actions,'Invite to match',async()=>{await api('invite',{playerId:player.id});$('notice').textContent='Match invitation sent to '+player.name+'.';await refresh()})}
function renderResults(){ $('results').replaceChildren(); for(const player of searchPlayers){const actions=entry($('results'),player.name,'Player '+player.id.slice(0,6));socialActions(actions,player)} }
function render(){for(const id of ['matches','friends','requests','invitations'])$(id).replaceChildren();
 for(const match of lobby.matches){const opponent=match.players.find(player=>player.id!==lobby.player.id);const yourTurn=match.status!=='finished'&&match.seatIndex===match.currentTurnSeatIndex;const detail=match.status==='finished'?(match.winnerSeatIndex===match.seatIndex?'You won':'Match finished'):match.status==='waiting'?'Waiting for another player':yourTurn?'Your turn · Round '+match.turnNumber:'Waiting for '+(opponent?.name||'opponent')+' · Round '+match.turnNumber;const actions=entry($('matches'),opponent?'You & '+opponent.name:'Open 7×7 match',detail);play(actions,match,match.status==='waiting'?'Open waiting game':match.status==='finished'?'View match':'Play');if(match.status==='waiting')button(actions,'Cancel waiting match',async()=>{await api('matches/'+match.id+'/cancel',{});$('notice').textContent='Waiting match cancelled.';await refresh()});if(opponent)socialActions(actions,opponent)}if(!lobby.matches.length)empty($('matches'),'No matches yet. Find an online match or invite a friend.');
 for(const link of lobby.friendships){if(link.status==='accepted'){const actions=entry($('friends'),link.player.name);button(actions,'Invite to match',async()=>{await api('invite',{playerId:link.player.id});$('notice').textContent='Match invitation sent.';await refresh()});button(actions,'Remove friend',async()=>{await api('friend-answer',{id:link.id,action:'remove'});await refresh()})}else{const actions=entry($('requests'),link.player.name,link.incoming?'Wants to be your friend':'Request sent');if(link.incoming){button(actions,'Accept',async()=>{await api('friend-answer',{id:link.id,action:'accept'});await refresh()},false);button(actions,'Decline',async()=>{await api('friend-answer',{id:link.id,action:'decline'});await refresh()})}else button(actions,'Cancel request',async()=>{await api('friend-answer',{id:link.id,action:'remove'});await refresh()})}}
 if(!lobby.friendships.some(link=>link.status==='accepted'))empty($('friends'),'Add players from a match or search below.');if(!lobby.friendships.some(link=>link.status==='pending'))empty($('requests'),'No pending friend requests.');
 const pending=lobby.invites.filter(invite=>invite.status==='pending');for(const invite of pending){const actions=entry($('invitations'),invite.player.name,invite.incoming?'Invited you to a 7×7 match':'Invitation sent');if(invite.incoming){button(actions,'Accept & play',async()=>{const result=await api('invite-answer',{id:invite.id,action:'accept'});location.assign('/?match='+result.match.id)},false);button(actions,'Decline',async()=>{await api('invite-answer',{id:invite.id,action:'decline'});await refresh()})}else button(actions,'Cancel invitation',async()=>{await api('invite-answer',{id:invite.id,action:'cancel'});await refresh()})}if(!pending.length)empty($('invitations'),'No pending match invitations.');renderResults();
}
async function refresh(){lobby=await api('lobby');render()}
async function run(action){if(busy)return;busy=true;$('error').textContent='';document.querySelectorAll('button:not(#enable-push):not(#disable-push):not(#test-push):not(#install-app)').forEach(button=>button.disabled=true);try{await action()}catch(error){$('error').textContent=error.message}finally{busy=false;document.querySelectorAll('button:not(#enable-push):not(#disable-push):not(#test-push):not(#install-app)').forEach(button=>button.disabled=false)}}
$('find').addEventListener('click',()=>run(async()=>{const result=await api('find',{version:VERSION});location.assign('/?match='+result.match.id)}));$('refresh').addEventListener('click',()=>run(refresh));
$('search-form').addEventListener('submit',event=>{event.preventDefault();run(async()=>{const result=await api('search?q='+encodeURIComponent($('query').value.trim()));searchPlayers=result.players;renderResults();if(!result.players.length)empty($('results'),'No approved player found. Ask your friend to sign in first, or try their exact registered email address.')})});
run(refresh);setInterval(()=>{if(!document.hidden&&!busy)run(refresh)},10000);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!busy)run(refresh)});
`,
  });
}
